apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: awh0fm3pl-go 
  janus-idp.io/tekton: awh0fm3pl-go
  backstage.io/kubernetes-id: awh0fm3pl-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: awh0fm3pl-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  